# All 'secret' configurations goes in here. 
# This file should be in .gitignore
# There should also be a secret_configuration.yml.example with fields blanked out.

development:
  facebook_secret_id: "297644757023528"
  facebook_secret_key: "794dc42b53a3c7172dd6848ff1808b5b"
